// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineShopping.Database;

namespace OnlineShopping.Database.Migrations
{
    [DbContext(typeof(OnlineShoppingContext))]
    [Migration("20220328192151_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OnlineShopping.Database.Entity.Activity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ActivityRecord")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ActivitySessionId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActivitySessionId");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("OnlineShopping.Database.Entity.ActivitySession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Session")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Session");

                    b.ToTable("ActivitySessions");
                });

            modelBuilder.Entity("OnlineShopping.Database.Entity.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Branch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Branch = "Apple",
                            Color = "Blue",
                            CreatedDate = new DateTime(2022, 3, 29, 2, 21, 50, 728, DateTimeKind.Local).AddTicks(4049),
                            Name = "Iphone13",
                            Price = 1200m
                        },
                        new
                        {
                            Id = 2L,
                            Branch = "Apple",
                            Color = "Green",
                            CreatedDate = new DateTime(2022, 3, 29, 2, 21, 50, 731, DateTimeKind.Local).AddTicks(1793),
                            Name = "Iphone13",
                            Price = 1200m
                        },
                        new
                        {
                            Id = 3L,
                            Branch = "Apple",
                            Color = "Gray",
                            CreatedDate = new DateTime(2022, 3, 29, 2, 21, 50, 731, DateTimeKind.Local).AddTicks(1883),
                            Name = "Iphone13",
                            Price = 1200m
                        },
                        new
                        {
                            Id = 4L,
                            Branch = "Samsung",
                            Color = "White",
                            CreatedDate = new DateTime(2022, 3, 29, 2, 21, 50, 731, DateTimeKind.Local).AddTicks(1899),
                            Name = "Galaxy Z Fold3",
                            Price = 900m
                        },
                        new
                        {
                            Id = 5L,
                            Branch = "Samsung",
                            Color = "Gray",
                            CreatedDate = new DateTime(2022, 3, 29, 2, 21, 50, 731, DateTimeKind.Local).AddTicks(1914),
                            Name = "Galaxy Z Fold3",
                            Price = 900m
                        });
                });

            modelBuilder.Entity("OnlineShopping.Database.Entity.Activity", b =>
                {
                    b.HasOne("OnlineShopping.Database.Entity.ActivitySession", "ActivitySession")
                        .WithMany("Activities")
                        .HasForeignKey("ActivitySessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActivitySession");
                });

            modelBuilder.Entity("OnlineShopping.Database.Entity.ActivitySession", b =>
                {
                    b.Navigation("Activities");
                });
#pragma warning restore 612, 618
        }
    }
}
